baseurl: /2019/did-wg
groupid: TBD
charter: /2019/@@@TBD@@@
wgname_lc: template
wgname_uc: TEMPLATE
github: https://github.com/w3c/@@@/


#theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules/

collections:
  minutes:
    output: true
    permalink: /Meetings/Minutes/:name
