baseurl: /2019/did-wg
groupid: 117488
charter: /2019/@@@TBD@@@
wgname_db: did
wgname_lc: did-wg
wgname_uc: TEMPLATE
github: https://github.com/w3c/template/
extra_call_id: did-topic



#theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules/

collections:
  minutes:
    output: true
    permalink: /Meetings/Minutes/:name
